/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.objetos_perdidos.UI;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import proyecto.objetos_perdidos.Conexion.CRegistro;

/**
 *
 * @author Hexaw
 */
public class agregar_objeto extends javax.swing.JDialog {

    /**
     * Creates new form agregar_objeto
     */
    String correo_usuario;
    Boolean confirmacion = false;
    int ID = 0;
    
    public Boolean getConfirmacion(){
        return confirmacion;
    }
    public agregar_objeto(java.awt.Frame parent, boolean modal,String c,Boolean b) {
        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
        this.correo_usuario=c;
        if(b==true){
            System.out.println(b);
            btn_editar.setEnabled(true);
            btn_guardar.setEnabled(false);
        }
        if(b==false){
            System.out.println(b);
            btn_editar.setEnabled(false);
            btn_guardar.setEnabled(true);
        }
    }
    
    public void llenar_editar(String tipo, String obj, String ubicacion, String descripcion,int id){
        cb_tipo_objeto.setSelectedItem(tipo);
        cb_objeto.setSelectedItem(obj);
        txt_ubicación.setText(ubicacion);
        txt_descripcion.setText(descripcion);
        ID=id;
    }
    public String[] datos(String dat){
        String[] informacion = new String[5];
        if(dat.equalsIgnoreCase("Electrónicos")){
            informacion[0]= "Celular";
            informacion[1] = "Portatil";
            informacion[2] = "Tablet";
            informacion[3] = "Audífonos";
            informacion[4] = "Otro";
        }
        if(dat.equalsIgnoreCase("Ropa")){
            informacion[0]= "Chaqueta";
            informacion[1] = "Aretes";
            informacion[2] = "Reloj";
            informacion[3] = "Bufanda";
            informacion[4] = "Otro";
        }
        if(dat.equalsIgnoreCase("Documento")){
            informacion[0]= "Cédula";
            informacion[1] = "Carnet universitario";
            informacion[2] = "Licencia de conducción";
            informacion[3] = "Tarjeta de indentidad";
            informacion[4] = "Otro";
        }
        if(dat.equalsIgnoreCase("Accesorio")){
            informacion[0]= "Maleta/bolso";
            informacion[1] = "Llavero";
            informacion[2] = "Sombrilla";
            informacion[3] = "Botilito";
            informacion[4] = "Otro";
        }
        if(dat.equalsIgnoreCase("Otro")){
            informacion[0] ="-";
        }
        
        
        return informacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_tipo_objeto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cb_objeto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_ubicación = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar objeto perdido");

        jLabel1.setText("Agregar objeto");

        jLabel2.setText("Tipo de objeto");

        cb_tipo_objeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Electrónicos", "Ropa", "Documento", "Accesorio", "Otro" }));
        cb_tipo_objeto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipo_objetoItemStateChanged(evt);
            }
        });

        jLabel3.setText("Objeto");

        cb_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_objetoActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripción");

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion);

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Encontrado en");

        txt_ubicación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ubicaciónActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ubicación)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_objeto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_tipo_objeto, 0, 156, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_editar)
                                .addGap(12, 12, 12)
                                .addComponent(btn_cancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_tipo_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ubicación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_editar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cb_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_objetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_objetoActionPerformed

    private void txt_ubicaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ubicaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ubicaciónActionPerformed

    private void cb_tipo_objetoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipo_objetoItemStateChanged
        if(evt.getStateChange()== ItemEvent.SELECTED){
            if(this.cb_tipo_objeto.getSelectedIndex()>0){
                this.cb_objeto.setModel(new DefaultComboBoxModel(this.datos(this.cb_tipo_objeto.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_cb_tipo_objetoItemStateChanged

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if(txt_ubicación.getText().equals("") && txt_descripcion.getText().equals("") && cb_tipo_objeto.getSelectedItem().toString().equalsIgnoreCase("Otro") ){
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos para hacer el registro");
        }
        if(cb_tipo_objeto.getSelectedItem().toString().equalsIgnoreCase("Seleccionar")){
            JOptionPane.showMessageDialog(null, "Debe ingresar valores válidos");
        }
        else{
            String tipo_obj = cb_tipo_objeto.getSelectedItem().toString();
            String obj = cb_objeto.getSelectedItem().toString();
            String ubicacion = txt_ubicación.getText();
            String descripcion = txt_descripcion.getText();
            
            CRegistro registro_objeto = new CRegistro();
            registro_objeto.registrar_objeto(tipo_obj, obj, ubicacion, descripcion, correo_usuario);
            this.dispose();
            confirmacion=true;
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if(txt_ubicación.getText().equals("") && txt_descripcion.getText().equals("") && cb_tipo_objeto.getSelectedItem().toString().equalsIgnoreCase("Otro") ){
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos para hacer el registro");
        }
        if(cb_tipo_objeto.getSelectedItem().toString().equalsIgnoreCase("Seleccionar")){
            JOptionPane.showMessageDialog(null, "Debe ingresar valores válidos");
        }
        else{
            CRegistro actualizacion = new CRegistro();
            actualizacion.Editar_objeto(cb_tipo_objeto.getSelectedItem().toString(),cb_objeto.getSelectedItem().toString(),txt_ubicación.getText(),txt_descripcion.getText(),ID);
            confirmacion=true;
            this.dispose();
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_objeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_objeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_objeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_objeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                agregar_objeto dialog = new agregar_objeto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cb_objeto;
    private javax.swing.JComboBox<String> cb_tipo_objeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_ubicación;
    // End of variables declaration//GEN-END:variables
}
